using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProcioneMGR.Data;

#nullable disable

namespace ProcioneMGR.Migrations.Postgres.Migrations
{
    /// <summary>
    /// [Revisione completa, 2026-09-05] <b>La tabella degli episodi del carry.</b> Il forward test del
    /// carry — l'unica classe di edge misurata positiva — non persisteva nulla: stato in memoria,
    /// funding incassato mai accumulato, sei «aperture» a ogni rischieramento del pod. Questa tabella
    /// è la misura che mancava; la scrive il pod (<c>CarryWorker</c>) e la legge il guscio.
    ///
    /// <para>Scritta a mano e idempotente (<c>IF NOT EXISTS</c>), come tutte le migrazioni di questo
    /// repo dal 2026-09-02: <c>migrations add</c> scaffolda dalla baseline sbagliata. Espansione
    /// pura: nessuna colonna esistente viene toccata, un binario precedente non se ne accorge.</para>
    /// </summary>
    // I DUE ATTRIBUTI NON SONO CERIMONIA: senza, EF non vede la migrazione (2026-09-02, #131).
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905143000_AddCarryLedger")]
    public partial class AddCarryLedger : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "CarryLedger" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Symbol" character varying(16) NOT NULL,
                    "Mode" character varying(8) NOT NULL,
                    "OpenedUtc" timestamp without time zone NOT NULL,
                    "ClosedUtc" timestamp without time zone NULL,
                    "NotionalQuote" numeric NOT NULL,
                    "EntryAnnualizedPercent" numeric NOT NULL,
                    "ExitAnnualizedPercent" numeric NULL,
                    "FundingEventsAccrued" integer NOT NULL DEFAULT 0,
                    "FundingCollectedPercent" numeric NOT NULL DEFAULT 0,
                    "FundingCollectedQuote" numeric NOT NULL DEFAULT 0,
                    "LastFundingUtc" timestamp without time zone NULL,
                    "CostPercent" numeric NOT NULL DEFAULT 0,
                    "NetQuote" numeric NULL,
                    "ClosedReason" character varying(200) NULL,
                    CONSTRAINT "PK_CarryLedger" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql(
                """CREATE INDEX IF NOT EXISTS "IX_CarryLedger_Symbol_ClosedUtc" ON "CarryLedger" ("Symbol", "ClosedUtc");""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "CarryLedger";""");
        }
    }
}
